#!/usr/bin/env python

from string import printable, whitespace
from random import randint

alphabet = [char for char in printable if char not in whitespace]

def get_pass(length=14):
    print(''.join([alphabet[randint(0, len(alphabet)-1)] for _ in range(length)]))

if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        get_pass(int(sys.argv[1]))
    else:
        get_pass()
